config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :borrows, except: :index
  end

  resources :borrows, only: :index do
    member do
      put :approve
      put :deny
    end
  end  
  devise_for :users
  get 'welcome', to: 'home#welcome'
  root 'books#index'
  resources :admin
  get 'approved', to: 'admin#approved'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :category
    has_many :borrows
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 10000 }
    validates :author, presence: true

    has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/borrow.rb
class Borrow < ApplicationRecord
    belongs_to :book
    belongs_to :user

    STATUSES = %w(approved denied pending)

    scope :pending, -> { where(status: :pending) }
    scope :approved, -> { where(status: :approved) }
    scope :denied, -> { where(status: :denied) }

    validates :status, inclusion: { in: Borrow::STATUSES }
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
    
end

app/models/user.rb
class User < ApplicationRecord
 has_many :borrows
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    
    before_action :require_admin_user

    def index
        @books = Book.all    

        @borrows = Borrow.all
    end

    def show
        @borrow = Borrow.find(params[:id])
    end
        



    def blacklist
        @user = User.all
        unless @borrow.user_id.returned
            
        

    end
    def show_user
        @user = user.all
    end

    private


    

    def require_admin_user
        unless current_user.admin?
            flash[:alert] = "Can't perform this operation"
            redirect_to root_path
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    before_action :require_admin_user, only: [:edit, :create, :update, :destroy]

    def index
        if params[:search]
            search_books
        end
        if params[:category].blank?
            @books = Book.paginate(page: params[:page], per_page: 8).order('created_at DESC')
        else
            @category_id = Category.find_by(name: params[:category]).id
            @books = Book.where(:category_id => @category_id).order('created_at DESC')
        end
    end

    def new
        @book =  Book.new
        @Categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def show
        @book = Book.find(params[:id])
    end
    
   

    def create
        @book = Book.new(book_params)
        
        if @book.save
            redirect_to root_path
        else
            flash[:error] = @book.errors.full_messages.join(", ")
            render 'new'
        end
    end

    def edit

    end

    def update
        if @book.update(book_params)
            redirect_to book_path (@book)
        else
            
            render 'edit'
        end  
    end

    def destroy
        @book.destroy
        redirect_to root_path
    end

    def search_books
        if @book = Book.all.find{|book| book.author.include?(params[:search])}
            redirect_to book_path(@book)
        else
            flash[:alert] = "Book not found"
        end
    end

    


    private
    def book_params
        params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
    end

    def find_book
        @book = Book.find(params[:id])
    end

    def require_admin_user
        unless current_user && current_user.admin?
            flash[:alert] = "Can't perform this operation"
            redirect_to root_path
        end
    end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
    before_action :find_book, only: [:new, :edit]
    before_action :find_borrow, only: [:edit, :update, :approve, :deny, :destroy]
    before_action :require_current_user
   
    def index
        @borrows = Borrow.all
    end    


    def new
        @borrow = @book.borrows.new()
    end
   
    def create
        @borrow = Borrow.new(borrow_params)
        @borrow.user = current_user
        if @borrow.save
            redirect_to current_user&.admin? ? borrows_path : book_path(@borrow.book)
        else
            render new
        end
    
    end

    def edit
       
    end

    def update
        if @borrow.update(borrow.params)
            redirect_to current_user&.admin? ? borrows_path : book_path(@borrow.book)
        else
            render 'edit'
        end
    end

    def approve
        @borrow.update(status: :approved)
        redirect_to borrows_path
    end
    
    def deny
        @borrow.update(status: :denied)
        redirect_to borrows_path
    end  

    def destroy
        @borrow.destroy
        redirect_to book_path(@book)
    end

    def return
        @book = Book.find(params[:id])
        invalid_return = false
        if @book.destroy && (@book.user_id != current_user.id)
            invalid_return = true
        end
        @book.destroy = false
        @book.user_id = nil
        if !invalid_return && @book.save!
            redirect_to @book, notice: 'Book was successfully returned.'
        else
            redirect_to root_path notice:  "Invalid Action!"
        end	
    end

    

    private

    def borrow_params
        params.require(:borrow).permit(:start_date, :end_date, :comment, :user_id, :book_id)
    end

    def find_book
        @book = Book.find(params[:book_id])
    end

    def find_borrow
        @borrow = Borrow.find(params[:id])
    end

    def require_current_user
        unless current_user
            flash[:alert] = "Can't perform this operation"
            redirect_to root_path
        end
    end

    def require_admin_user
        unless current_user&.admin?
            flash[:alert] = "Can't perform this operation unless you're an Admin"
            redirect_to root_path
        end
    end    

   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  def welcome
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrow_helper.rb
module BorrowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/approved.html.erb
approval

app/views/admin/index.html.erb
this is the admin page

<div>
    <table>
        
        <%= render @borrows.all %>
    </table>
</div>

    
   

app/views/books/_form.html.erb
<div class="ui  ">
    <div class="ui column  grid">
        <div class="column">
            <%= form_for @book, :html => {:multipart => true} do |f| %>
                <div class="ui form">
                    <div class="field">
                        <%= f.collection_select :category_id, Category.order(name: :asc), :id, :name, {include_blank: 'Select Category'} %>
                    </div>
                    <div class="field">
                        <%= f.file_field :book_img %>
                    </div>
                    <div class="field">
                        <%= f.label :Title %>
                        <%= f.text_field :title, class:'ui left icon input',placeholder:'title' %>
                    </div>
                    <div class="field">
                        <%= f.label :Description %>
                        <%= f.text_area :description, class:'ui left icon input',placeholder:'description' %>
                    </div>
                    <div class="field">
                        <%= f.label :Author %>
                        <%= f.text_field :author, class:'ui left icon input',placeholder:'author' %>
                    <i class="user icon"></i>
                    </div>
                </div>
                <%= f.submit class:"ui primary button"  %>
            <% end %>
        </div>
    </div>
</div>    

app/views/books/edit.html.erb
<%= render "books/form" %>

app/views/books/index.html.erb
<div align= 'center'>
     <%= form_tag(books_path, method: :get) do %>
        <p> Search for an Author </p>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Search") %>
    <% end %>
</div><br>


<% if @books.count == 0 %>
    <h2>There are books currently in this category</h2>
<% else %>
    <div class="ui grid">
        <% @books.each do |book| %>
            <div class="four wide column">
                <a href="/books/<%=book.id %>">
                    <%= image_tag book.book_img.url(:book_index), class:'book' %>
                </a>
            </div>
        <% end %>
    </div>

<% end %>
<div class="bottom" align= 'center'>
    <%= will_paginate @collection, renderer: WillPaginateSemanticUi::ActionView::Renderer %>
</div>

app/views/books/new.html.erb
<h1>Books Listing</h1>

<%= render "books/form" %>

app/views/books/show.html.erb
<div class="ui grid">
    <div class="two wide column">
        <div class="">
            <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
        </div>
    </div>
    <div class="now eight wide column">
        <div class="ui segment"> 
            <h2><%= @book.title %></h2>
            <h2><%= @book.author%></h2>
            <p><%= @book.description%></p>
        </div>
    </div>
</div>

<%= link_to "Book Borrowing Request", new_book_borrow_path(@book) %>



<div class="ui container">
    <%= link_to "Back", root_path %> <br>

    <% if current_user.admin? %>
        <%= link_to 'Edit', edit_book_path %> &nbsp;&nbsp; 
        <%= link_to 'Delete', book_path, method: :delete, data: {confirm:'Are your sure?'}  %>
    <% end %>
</div>

app/views/borrows/_form.html.erb
<div class="ui  ">
    <div class="ui column  grid">
        <div class="column">
            <%= form_for ([@book, @borrow]) do |f| %>
                <div class="ui form">
                    <%=f.hidden_field :book_id, value: @book.id %>
                    <div class="field">
                            <%= f.label :start_date %>
                            <%= f.date_field :start_date, class:'ui left icon input',placeholder:'Start_date' %>
                    </div>
                    <div class="field">
                        <%= f.label :End_date %>
                        <%= f.date_field :end_date, class:'ui left icon input',placeholder:'End_date' %>
                    </div>
                    <div class="field">
                        <%= f.label :comment %>
                        <%= f.text_field :comment, class:'ui left icon input',placeholder:'State reason to borrow' %>
                    <i class="user icon"></i>
                    </div>
                </div>
                <%= f.submit class:"ui primary button"  %>
            <% end %>
        </div>
    </div>
</div>    

app/views/borrows/edit.html.erb
<div class="ui  ">
    <div class="ui column  grid">
        <div class="column">
            <%= form_for ([@book, @borrow]) do |f| %>
                <div class="ui form">
                    <div class="field">
                            <%= f.label :start_date %>
                            <%= f.date_field :start_date, class:'ui left icon input',placeholder:'Start_date' %>
                    </div>
                    <div class="field">
                        <%= f.label :End_date %>
                        <%= f.date_field :end_date, class:'ui left icon input',placeholder:'End_date' %>
                    </div>
                    <div class="field">
                        <%= f.label :comment %>
                        <%= f.text_field :comment, class:'ui left icon input',placeholder:'State reason to borrow' %>
                    <i class="user icon"></i>
                    </div>
                </div>
                <%= f.submit class:"ui primary button"  %>
            <% end %>
        </div>
    </div>
</div>

app/views/borrows/index.html.erb
<table class="ui celled table">
    <thead>
    <tr>
        <th>Name</th>
        <th>State Date</th>
        <th>End Date</th>
        <th>Comment</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
        <%- @borrows.each do |borrow| %>
        <tr>
            <td><%= borrow.user.email %></td>
            <td><%= borrow.start_date %></td>
            <td ><%= borrow.end_date %></td>
            <td ><%= borrow.comment %></td>
            <td ><%= borrow.status %></td>
            <td ><% if current_user.admin? %>
                <%= link_to "Approve", approve_borrow_path(borrow), method: :put %>
                <%= link_to "Deny", deny_borrow_path(borrow), method: :put %>
            <% end %>
            <%= link_to "Delete request", book_borrow_path(borrow.book, borrow), method: :delete, data: {confirm: "Are you sure"} %>
        </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/borrows/new.html.erb
<%= render 'borrows/form' %>

app/views/home/index.html.erb
<h2 class="ui center aligned medium blue icon header">
    <i class="circular inverted book icon"></i>
    Readers are leaders
</h2>

<%= link_to "sign out", destroy_user_session_path, method: :delete %>
<div class="ui equal width center aligned padded grid">
    <div class="row">
    <div class="olive column">
        <h2>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
            Provident molestias optio quo enim dolorum ullam molestiae sit 
            omnis temporibus sed voluptas nostrum vel ratione voluptates, quam velit cum vitae. Vitae!
        </h2>
    </div>
    <div class=" black column">
        <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
            Voluptates similique nihil vel. Quos facere facilis molestiae voluptas voluptatem 
            possimus numquam et id voluptatum veritatis laudantium, deserunt corporis iusto ipsa dolores.
        </h2>
    </div>
    </div>
    <div class="row" style="background-color: #869D05;color: #FFFFFF;">
    <div class="column">Readers digest</div>
    </div>
    <div class="row">
    <div class="black column">
        <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Excepturi facere mollitia eveniet aperiam, eum nesciunt. 
            Totam non quas impedit et ad optio nobis provident, inventore 
            corrupti accusantium! Eius, reprehenderit obcaecati!
        </h2>
    </div>
    <div class="olive column">
        <h2>Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
            Placeat veritatis veniam non suscipit natus sint quae quisquam libero harum autem laborum repudiandae, 
            nulla adipisci doloremque velit rerum blanditiis unde ipsam.
        </h2>
    </div>
    </div>
</div>

  <div class="ui two column grid">
    
    <%= image_tag "library.jpeg", style: 'height:200%;width:50%;' %>
    <%= image_tag "books.jpeg", style: 'height:310px;width:50%;' %>
  </div> 
    

app/views/home/welcome.html.erb
<h2 class="ui center aligned medium blue icon header">
    <i class="circular inverted book icon"></i>
    Readers are leaders
</h2>

<%= link_to "sign out", destroy_user_session_path, method: :delete %>
<div class="ui equal width center aligned padded grid">
    <div class="row">
    <div class="olive column">
        <h2>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
            Provident molestias optio quo enim dolorum ullam molestiae sit 
            omnis temporibus sed voluptas nostrum vel ratione voluptates, quam velit cum vitae. Vitae!
        </h2>
    </div>
    <div class=" black column">
        <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
            Voluptates similique nihil vel. Quos facere facilis molestiae voluptas voluptatem 
            possimus numquam et id voluptatum veritatis laudantium, deserunt corporis iusto ipsa dolores.
        </h2>
    </div>
    </div>
    <div class="row" style="background-color: #869D05;color: #FFFFFF;">
    <div class="column">Readers digest</div>
    </div>
    <div class="row">
    <div class="black column">
        <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Excepturi facere mollitia eveniet aperiam, eum nesciunt. 
            Totam non quas impedit et ad optio nobis provident, inventore 
            corrupti accusantium! Eius, reprehenderit obcaecati!
        </h2>
    </div>
    <div class="olive column">
        <h2>Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
            Placeat veritatis veniam non suscipit natus sint quae quisquam libero harum autem laborum repudiandae, 
            nulla adipisci doloremque velit rerum blanditiis unde ipsam.
        </h2>
    </div>
    </div>
</div>

  <div class="ui two column grid">
    
    <%= image_tag "library.jpeg", style: 'height:200%;width:50%;' %>
    <%= image_tag "books.jpeg", style: 'height:310px;width:50%;' %>
  </div> 
    

app/views/layouts/_navigation.html.erb
<div class="ui olive inverted menu">
    <div class="ui container">
        <%= link_to 'Home', welcome_path, class: 'item' %> 
        <% if user_signed_in? %>
            <%= link_to 'Readers Guide', books_path, class: 'item' %>
        <% end %>
        <div class="right menu">
            <% if user_signed_in? %>
                <div class="ui dropdown item">
                    Category<i class="dropdown icon"></i>
                    <div class="menu">
                        <% Category.all.each do|category| %>
                            <%= link_to category.name, books_path(category: category.name) , class:'item' %>
                        <% end %>
                    </div>
                </div>
                <div class="ui dropdown item">
                    <%= 'Admin' if current_user.admin? %> 
                    Profile<i class="dropdown icon"></i>
                    <div class="menu">
                        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'item' %>
                        <% if current_user.admin? %>
                         <%= link_to "Add Book", new_book_path , class:'item' %>
                        <% end %>
                        <a class="item">Spanish</a>
                    </div>
                </div>
                
            <% else %>
                <div class="item">
                    <%= link_to "Log In", new_user_session_path, class:"ui primary button" %>
                </div>

                <div class="item">
                    <%= link_to "Create Account", new_user_registration_path, class:"ui primary button" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readers Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>